spring:
  data:
    mongodb:
      user: praakhya
      password: project123
      uri: mongodb+srv://praakhya:project123@cluster0.4dyf8jd.mongodb.net/sample_mflix

application:
  security:
    jwt:
      secret-key-file: jwt_signing_key.pem
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
