spring:
  data:
    mongodb:
      user: test
      uri: mongodb://localhost:27017/authentication

application:
  security:
    jwt:
      secret-key-file: jwt_signing_key.pem
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
